### PR TITLE
Update to latest console release 1.0-beta5.

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by sylus** [comment]
Hmm it looks like something has changed in 1.0-beta5 causing failure in Travis Buil. Will have to look into.

**Comment by sylus** [comment]
I'm pretty sure this is a bug in console, when I run make build locally and test the containers the output I am getting is:

```sh
Step 5 : RUN drupal --version
 ---> Running in ea015ed02d6b

Warning: Invalid argument supplied for foreach() in /composer/vendor/drupal/console/src/Utils/RequirementChecker.php on line 71
"Drupal Console" version "1.0.0-beta5"
```

**Comment by sylus** [comment]
Looks like that isn't why Travis is failing though, only the dev-master container can't build.

**Comment by sylus** [comment]
See discussion here:

https://github.com/hechoendrupal/DrupalConsole/issues/2590#issuecomment-240197606

This will be fixed on RC release, at which point I will do a new release. ^_^

**Comment by bmcclure** [comment]
There have been I believe 15 RC releases so far. Do you think it's more likely we'll be able to get a working updated release of this project now?

**Pull request closed without merging**
