### PR TITLE
Update to latest console release 1.0-beta4.

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by RobLoach** [comment]
Testing here worked. Merged. Well done :+1:

**Comment by sylus** [comment]
Woot thx! :)

**Comment by RobLoach** [comment]
Looks like tests are breaking though. I'll go through testing again.

**Comment by sylus** [comment]
Tests are fine just couldn't pull from P.R. at that point in time :) Everything successfully built on docker hub ^_^

**Comment by sylus** [comment]
https://hub.docker.com/r/drupalconsole/console/builds/

**Pull request merged**
